"""Database layer: one small set of functions that works with two databases.

  - On your own computer the words live in a SQLite file (flashcards.db). Nothing to set up.
  - Online (Vercel + Neon) they live in Postgres. Set the DATABASE_URL setting to switch to it.

The rest of the app only calls get_db() and ensure_schema(). It never needs to know which database is behind them.
"""
import os
import shutil
import sqlite3
from contextlib import closing, contextmanager
from pathlib import Path

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:   # fine for local use: SQLite works without the Postgres driver
    psycopg = None

BASE_DIR = Path(__file__).parent
DB_PATH = BASE_DIR / "flashcards.db"     # the SQLite file used when DATABASE_URL is not set

# What to catch when a save breaks a rule such as "this word already exists" (the same idea in both databases).
INTEGRITY_ERRORS = (sqlite3.IntegrityError,) + ((psycopg.IntegrityError,) if psycopg else ())


def database_url():
    return os.environ.get("DATABASE_URL", "").strip()


def using_postgres():
    return database_url().startswith(("postgres://", "postgresql://"))


class Connection:
    """Wraps a real connection so the app can write one kind of SQL for both databases.
    It turns the `?` placeholders (SQLite style) into `%s` (Postgres style) when needed."""

    def __init__(self, raw, postgres):
        self.raw = raw
        self.postgres = postgres

    def execute(self, sql, params=()):
        if self.postgres:
            sql = sql.replace("?", "%s")
        return self.raw.execute(sql, params)


@contextmanager
def get_db():
    """Open a database connection. On leaving the `with` block the changes are saved, or undone if something went
    wrong, and the connection is closed. Rows can be read by column name: row["english"]."""
    if using_postgres():
        if psycopg is None:
            raise RuntimeError("DATABASE_URL points at Postgres, but the psycopg package is not installed.")
        raw = psycopg.connect(database_url(), row_factory=dict_row, connect_timeout=10)
        conn = Connection(raw, True)
    else:
        raw = sqlite3.connect(DB_PATH)
        raw.row_factory = sqlite3.Row             # lets us read columns by name
        raw.execute("PRAGMA foreign_keys = ON")   # make SQLite enforce "a word must belong to a real user"
        conn = Connection(raw, False)
    try:
        yield conn
        raw.commit()
    except Exception:
        raw.rollback()
        raise
    finally:
        raw.close()


# ---------- Creating the tables ----------

POSTGRES_SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS users (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        kind        TEXT NOT NULL DEFAULT 'guest',
        google_sub  TEXT UNIQUE,
        email       TEXT,
        created     TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS words (
        id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id  BIGINT REFERENCES users(id) ON DELETE CASCADE,
        english  TEXT NOT NULL,
        thai     TEXT NOT NULL,
        created  TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (user_id, english)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_words_user ON words (user_id)",
    """
    CREATE TABLE IF NOT EXISTS usage_counts (
        subject  TEXT NOT NULL,
        bucket   TEXT NOT NULL,
        kind     TEXT NOT NULL,
        n        BIGINT NOT NULL DEFAULT 0,
        PRIMARY KEY (subject, bucket, kind)
    )
    """,
]


def ago_sql(days):
    """SQL for 'this many days ago'. The two databases write it differently."""
    days = int(days)
    if using_postgres():
        return f"now() - interval '{days} days'"
    return f"datetime('now', '-{days} days')"


def _init_postgres():
    with get_db() as conn:
        # Two server instances can start at the same moment (this happens online). The lock makes the second one
        # wait until the first has finished creating the tables, instead of both trying at once.
        conn.execute("SELECT pg_advisory_xact_lock(727274)")
        for statement in POSTGRES_SCHEMA:
            conn.execute(statement)


def _words_table_needs_migration():
    """True if flashcards.db was made by an older version: a words table with no user_id column."""
    if not DB_PATH.exists():
        return False
    with closing(sqlite3.connect(DB_PATH)) as probe:
        columns = [row[1] for row in probe.execute("PRAGMA table_info(words)")]
    return bool(columns) and "user_id" not in columns


def _init_sqlite():
    """An older single-user database is upgraded in place: a backup copy is made first, and the old words are kept
    with no owner (user_id empty) so they are never shown to a stranger. They can be claimed by an account later."""
    migrate = _words_table_needs_migration()
    if migrate:
        shutil.copy2(DB_PATH, DB_PATH.with_name(DB_PATH.name + ".before-users.bak"))

    with get_db() as conn:
        conn.execute("BEGIN")   # everything below succeeds together or not at all
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                kind        TEXT NOT NULL DEFAULT 'guest',
                google_sub  TEXT UNIQUE,
                email       TEXT,
                created     TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        if migrate:
            conn.execute("ALTER TABLE words RENAME TO words_old")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS words (
                id       INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id  INTEGER REFERENCES users(id) ON DELETE CASCADE,
                english  TEXT NOT NULL,
                thai     TEXT NOT NULL,
                created  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (user_id, english)
            )
            """
        )
        if migrate:
            conn.execute(
                "INSERT INTO words (id, user_id, english, thai, created) "
                "SELECT id, NULL, english, thai, created FROM words_old"
            )
            conn.execute("DROP TABLE words_old")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_words_user ON words (user_id)")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS usage_counts (
                subject  TEXT NOT NULL,
                bucket   TEXT NOT NULL,
                kind     TEXT NOT NULL,
                n        INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (subject, bucket, kind)
            )
            """
        )


def init_db():
    """Create the tables if they are missing. Safe to run every time."""
    if using_postgres():
        _init_postgres()
    else:
        _init_sqlite()


_schema_ready = False


def ensure_schema():
    """Run init_db() once per server process. Online, there is no 'start-up' step we control, so the app calls this
    before its first request; after that it costs nothing."""
    global _schema_ready
    if not _schema_ready:
        init_db()
        _schema_ready = True
